server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:3f8b2e9d1a7c4f6e0b5d8a2c7e4f1b9d3a6c8e2f5b7d0a4c9e3f6b1d8a5c2e7f}
    expiration: 86400000

spring:
  application:
    name: saas-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://metro.proxy.rlwy.net:16640/railway}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:ZbGScXxpRLQAbWvafoLjyQUrRlAlQLQi}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:pkc-921jm.us-east-2.aws.confluent.cloud:443}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_KEY:PLEBR6UYY7MPF7OL}" password="${KAFKA_SECRET:cfltBtw7nBj1x94Qj4myAkIiudarkeqfCwQur2U+L4CGjXWQy+hI0ChOo65zjixQ}";'
    consumer:
      group-id: saas-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 8000
        retries: 0

logging:
  level:
    root: INFO
    com.saas: DEBUG

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
